### ISSUE TITLE
De OAS-specificatie van het attribute `data` voldoet niet aan json definitie van CE

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/notificatieservices#120]
Deze OAS-specificatie:

```yaml
 data:
  type: object
  additionalProperties:
    type: string
  nullable: true
```

matched niet met de [JSON CE-definitie](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/cloudevents.json):

```json
"datadef": {
      "type": ["object", "string", "number", "array", "boolean", "null"]
```

Dus de OAS-definitie moet nog worden aangepast.
